services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./conf.d:/etc/nginx/conf.d
    depends_on:
      - oauth2_proxy
      - test_app

  oauth2_proxy:
    image: quay.io/oauth2-proxy/oauth2-proxy:latest
    container_name: oauth2_proxy
    environment:
      # Replace these with your Auth0 details
      - OAUTH2_PROXY_PROVIDER=oidc
      - OAUTH2_PROXY_OIDC_ISSUER_URL=${AUTH0_DOMAIN}/
      - OAUTH2_PROXY_CLIENT_ID=${AUTH0_CLIENT_ID}
      - OAUTH2_PROXY_CLIENT_SECRET=${AUTH0_CLIENT_SECRET}
      - OAUTH2_PROXY_REDIRECT_URL=http://localhost/oauth2/callback
      - OAUTH2_PROXY_EMAIL_DOMAINS=*
      - OAUTH2_PROXY_COOKIE_SECRET=${COOKIE_SECRET}

      # Additional settings for a smoother experience
      - OAUTH2_PROXY_REVERSE_PROXY=true
      - OAUTH2_PROXY_PASS_ACCESS_TOKEN=true
      - OAUTH2_PROXY_SET_XAUTHREQUEST=true
      # - OAUTH2_PROXY_COOKIE_REFRESH=15m
      # - OAUTH2_PROXY_CODE_CHALLENGE_METHOD=s256

    ports:
      - "4180:4180"
    command:
      - "--http-address=0.0.0.0:4180"

  test_app:
    build: ./app
    container_name: test_app
    ports:
      - "8080:80"
