services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx_conf/conf.d:/etc/nginx/conf.d:ro
      - ./nginx_conf/includes:/etc/nginx/includes:ro

    depends_on:
      - oauth2_proxy
      - test_app

  oauth2_proxy:
    image: quay.io/oauth2-proxy/oauth2-proxy:v7.5.1
    container_name: oauth2_proxy
    environment:
      - OAUTH2_PROXY_PROVIDER=oidc
      - OAUTH2_PROXY_OIDC_ISSUER_URL=${AUTH0_DOMAIN}/
      - OAUTH2_PROXY_CLIENT_ID=${AUTH0_CLIENT_ID}
      - OAUTH2_PROXY_CLIENT_SECRET=${AUTH0_CLIENT_SECRET}
      - OAUTH2_PROXY_REDIRECT_URL=http://localhost/oauth2/callback
      - OAUTH2_PROXY_EMAIL_DOMAINS=*
      - OAUTH2_PROXY_COOKIE_SECRET=${COOKIE_SECRET}
      - OAUTH2_PROXY_REVERSE_PROXY=true
      - OAUTH2_PROXY_PASS_ACCESS_TOKEN=true
      - OAUTH2_PROXY_SET_XAUTHREQUEST=true
      - OAUTH2_PROXY_COOKIE_REFRESH=15m
      - OAUTH2_PROXY_CODE_CHALLENGE_METHOD=S256
      - OAUTH2_PROXY_HTTP_ADDRESS=0.0.0.0:4180
      ## Don't disable COOKIE_SECURE on actual server with ssl
      - OAUTH2_PROXY_COOKIE_SECURE=false

    ports:
      - "4180:4180"

  test_app:
    build: ./app
    container_name: test_app
    ports:
      - "8080:80"
